import { useEffect, useState } from 'react'
import { Eye, EyeOff, Plus, Save, Upload } from 'lucide-react'
import { listPrivateClones, putPrivateClone, type PrivateClone } from './clonePrivateStore'
function blank(): PrivateClone { const now = new Date().toISOString(); return { id: crypto.randomUUID(), name: 'Novo clone', note: '', createdAt: now, updatedAt: now } }
export function PrivateCloneVault() {
 const [clones,setClones]=useState<PrivateClone[]>([]); const [selected,setSelected]=useState(''); const [visible,setVisible]=useState(false); const [loading,setLoading]=useState(true); const [message,setMessage]=useState('')
 useEffect(()=>{void listPrivateClones().then(items=>{setClones(items);setSelected(items[0]?.id??'')}).catch(error=>setMessage(error instanceof Error?error.message:'Falha no cofre.')).finally(()=>setLoading(false))},[])
 const clone=clones.find(item=>item.id===selected)
 const save=async(next:PrivateClone)=>{try{await putPrivateClone({...next,updatedAt:new Date().toISOString()});const items=await listPrivateClones();setClones(items);setSelected(next.id);setMessage('Alteração salva somente neste navegador.')}catch(error){setMessage(error instanceof Error?error.message:'Não foi possível salvar.')}}
 const chooseImage=async(file?:File)=>{if(!file||!clone)return;if(!file.type.startsWith('image/')||file.size>8*1024*1024){setMessage('Escolha uma imagem de até 8 MB.');return}await save({...clone,image:file});setVisible(true)}
 return <section className="glass-panel private-clone-vault"><div className="editorial-row"><div><span className="eyebrow">COFRE PRIVADO DE CLONES</span><h3>Referências pessoais</h3><p>As imagens ficam no armazenamento isolado deste navegador. Não são enviadas para GitHub, Vercel, IA externa ou galeria pública.</p></div><button type="button" onClick={()=>void save(blank())}><Plus size={15}/>Novo clone</button></div>{loading?<p>Carregando cofre privado…</p>:<div className="private-clone-layout"><aside>{!clones.length&&<p>Nenhum clone neste navegador.</p>}{clones.map(item=><button type="button" key={item.id} className={item.id===selected?'selected':''} onClick={()=>{setSelected(item.id);setVisible(false)}}><span>{item.image?'Imagem privada':'Sem imagem'}</span><strong>{item.name}</strong></button>)}</aside>{clone&&<div className="private-clone-editor"><div className="private-clone-preview">{visible&&clone.image?<img src={URL.createObjectURL(clone.image)} alt={`Referência privada de ${clone.name}`}/>:<div><EyeOff size={32}/><strong>Imagem protegida</strong><span>{clone.image?'Clique no olho para revelar localmente.':'Importe a referência para este navegador.'}</span></div>}<button type="button" className="private-eye" onClick={()=>setVisible(value=>!value)} aria-label={visible?'Ocultar imagem':'Mostrar imagem'}>{visible?<EyeOff size={18}/>:<Eye size={18}/>}</button></div><label>Nome do clone<input value={clone.name} maxLength={80} onChange={event=>setClones(items=>items.map(item=>item.id===clone.id?{...item,name:event.target.value}:item))}/></label><label>Notas de edição<textarea value={clone.note} maxLength={1000} rows={4} onChange={event=>setClones(items=>items.map(item=>item.id===clone.id?{...item,note:event.target.value}:item))} placeholder="Uso, aparência, versão, restrições…"/></label><div className="private-clone-actions"><label className="private-upload"><Upload size={15}/>Importar imagem privada<input type="file" accept="image/*" onChange={event=>void chooseImage(event.target.files?.[0])}/></label><button type="button" className="primary-button" onClick={()=>void save(clone)}><Save size={15}/>Salvar edição</button></div></div>}</div>}{message&&<p className="studio-saved">{message}</p>}</section>
}

